name: SoundExperience
favicon: null
layout_spectrum: 0.3427085652947426
typography_spectrum: 0.07142203114926815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#ffffff'
    - '#698368'
    - '#fead6b'
    - '#fe5758'
  brandStrength: 0.6370226554572582
  lightness: 0.2859140234068036
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
